version: '1.0'
services:

  api:
    container_name: api_v1
    image: node:20
    tty: true
    build: ./api        
    ports:
     - 5080:5080
    depends_on:
            mysql:
                condition: service_healthy 
    volumes:
     - .:/opt/src
    working_dir: /opt/src/api
    command: bash -c 'npm install -g npm@latest; npm run dev'
    env_file:
     - .env 
    restart: always  

  ui:
    container_name: ui_v1
    image: node:20
    tty: true
    build: ./ui
    ports:
     - "3000:3000"
    volumes:
     - .:/opt/src 
    working_dir: /opt/src/ui
    command: bash -c 'npm install -g npm@latest; npm run dev'
    env_file:
      - .env  
    restart: always    

  mysql:
    container_name: mysql_v1
    build: ./mysql
    ports:
      - 3306:3306
    env_file:
     - .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_USER: ${DATABASE_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD} 
    restart: always   
    healthcheck:
            test: ['CMD-SHELL', 'mysqladmin ping']
            interval: 1s
            timeout: 2s
            retries: 20
